### ISSUE TITLE
Tiered pricing

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1030]
connects to big-neon/bigneon#42
We can brainstorm a way to implement tiered pricing.
The end result is, I create a ticket_type with 1000 quantity and a price of $100.
Instead of ticket_pricing being a time based override, it uses a quantity drawdown. So the first batch of 500 tickets is $50, when those are sold out the next batch of 250 is $75. And once those are done, the default ticket price of $100 is used.

**Comment by zmelamed** [comment]
I'm working on the design/UX for this on the consumer side once we have that it'll be easier to think through the implementation

**Comment by zmelamed** [comment]
Why is this marked as `Urgent`?

**Comment by Krakaw** [comment]
We can un-urgent it

**Comment by Timo614** [comment]
@zmelamed hey Zach any update on the UX side of this? Noticed it was in the current sprint so was hoping to grab.

**Comment by philipr-za** [comment]
After brainstorming we decided to do this by adding a `Parent ticket type ID` to `TicketType` to chain a series of TicketTypes together. 

So the top parent `TicketType` will be visible and when it is sold out the `TicketType` that has the first type as its parent can then be made visible and so on

**Comment by Krakaw** [comment]
@zmelamed we've got a solution to this, let's just chat to confirm.

**Comment by Krakaw** [comment]
Part of the requirement is that the tiers can be changed either on a time expiry or on selling out.

**Comment by Krakaw** [comment]
@philipr-za let's chat before you start.

**Comment by zmelamed** [comment]
I see 2 ways to approach this...

If 2 is significantly more straightforward lets break that out as a separate issue to solve for this quickly because it solves the clients immediate issue.

1) Same sort of way we handle the time based expiry and everything roles up under the same ticket type name in reports
  - User enters Ticket name and [total quantity] and [default price]
  - Click Schedule price change
  - Select "Trigger based on [ ] Date/Time [ ] Quantity"
  - Same sort of interface as our fee schedule building grid. 
0 to ____ Price _____
____ to [total quantity] Price [default price]

2) Add an option to the Ticket type "Sale start date/time" to "When ticket sales end for..." which pulls up a dropdown of other ticket types that were added. (this is how EB does it).

**Comment by zmelamed** [comment]
I've create big-neon/bigneon#42 and big-neon/bigneon#41
