### ISSUE TITLE
Route `/events` shouldn't require a token to call

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#104]
Users need to be able search and view all events without creating an account yet.

**Comment by Timo614** [comment]
I'll quickly grab this one.

**Comment by Timo614** [comment]
One difficulty here is the way the middleware is being handled. We're associating it with a given resource but the only way to define two controller actions using the same path is to keep them in the same resource as well. 

What we have now, for example:

```
        .resource("/events", |r| {
            r.middleware(AuthMiddleware::new());
            r.method(Method::POST).with(events::create);
            r.method(Method::GET).with(events::index);
        })
```

The following won't work though as the index route is then ignored and it returns 404:

```
        .resource("/events", |r| {
            r.middleware(AuthMiddleware::new());
            r.method(Method::POST).with(events::create);
        })
        .resource("/events", |r| {
            r.method(Method::GET).with(events::index);
        })
```

I'm checking the docs if there's a way I can get around this otherwise may have to figure out a better way to associate the middleware with the given routes (not sure offhand how though but will look into it).

**Comment by Timo614** [comment]
Should the venues index and show actions require authentication (right now they do)?

Also in the associated PR I set the following routes so they didn't require it (venues has similar routes as well) but let me know if these should require authorization:

```
        .resource("/events/venues/{id}", |r| {
            r.method(Method::GET).with(events::show_from_venues);
        })
        .resource("/events/organizations/{id}", |r| {
            r.method(Method::GET).with(events::show_from_organizations);
        })
```
