### ISSUE TITLE
Holds without codes

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#1054]
Allow holds to have a nullable code, if the code is null, they cannot be added to a cart, but they can be split into a sub hold that does have a code.

**Comment by Jasonvdb** [comment]
@Krakaw holds created from adding a name to a list need a code at least. When checking out a ticket for that hold, the only way to get the discount/comp is to pass in that code.

**Comment by Krakaw** [comment]
Yes, you would not be able to access the tickets in the hold without a code.

**Comment by Jasonvdb** [comment]
Related to https://github.com/big-neon/bn-api/issues/1070

**Comment by Timo614** [comment]
@Krakaw @Jasonvdb is this intention here to ever sell the tickets that are part of the hold in this state? 

Is this just a means of setting aside a bunch of tickets that will be split off later into their own holds for redemption? Wondering if #1070 is needed or if the scenario it's setup for isn't something we need to support.

What case would we want to allow a box office person to purchase from a hold but wouldn't want to set a redemption code on it? I'd think we'd just split off x number of tickets for the box office if we ran into a situation like that and they'd have a code.

**Comment by Jasonvdb** [comment]
@Krakaw can probably answer better. But I was imagining a scenario where names are added to a hold. Like a promotor gives a few comps to the media for the general access ticket type. He doesn't want anyone redeeming these online so he doesn't give a redemption code. Now the box office agent can't checkout those tickets when the media guys arrive because we are always assuming there'll be a code for box office.

**Comment by Jasonvdb** [comment]
I guess one solution could be to make up a unique redemption code if one isn't supplied. 
What's happening right now in bn-web is tickets are being added to carts using a blank redemption code. Which then adds normal tickets and doesn't apply the discount/comp. So to the box office user, that behaviour is wrong.

**Comment by mikethetike** [comment]
We could also create a hidden redemption code for the hold and not show it on the front end. In my mind that is the same as passing through a hold's id. Doing it this way will mean that we don't have to change any code

**Comment by Timo614** [comment]
I pushed up what I had in progress here to make the column null: https://github.com/big-neon/bn-api/compare/master...Timo614:nullable-redemption-code-for-holds?expand=1 still needed to wrap it up and didn't include 1070 as I was waiting first on the feedback above.

@mikethetike so just to confirm you were thinking instead of having the column be nullable to add a boolean if the hold is private or not. If it's a private hold then we don't surface the `redemption_code` except in the admin tooling and we prevent non box-office orders from updating carts using redemption codes from private holds?

> But I was imagining a scenario where names are added to a hold. Like a promotor gives a few comps to the media for the general access ticket type. He doesn't want anyone redeeming these online so he doesn't give a redemption code. Now the box office agent can't checkout those tickets when the media guys arrive because we are always assuming there'll be a code for box office.

I think Mike's approach would work for this then. We'd just have the holds be private so only the box office agent could redeem them as the user would have no means to use the `redemption_code` even if they somehow found it was surfaced.

If that sounds good I'll nuke my branch and pivot to that approach let me know though if this other approach is more ideal. Is there any reason to continue with the `null` approach / this issue? I could add support for this as well if there's some use case for it in addition to the private approach.

**Comment by mikethetike** [comment]
Yeah, I think it's going to be less work to just add an `is_private` flag. If a person gets access to the "secret" redemption code, they would have already had access to the `hold.id`, we'd need to check the security level anyway.

**Comment by Timo614** [comment]
How does the user get access to the redemption code anyhow? Isn't it effectively private unless we give them the code? What would we be using the `is_private` flag to toggle?

> Like a promotor gives a few comps to the media for the general access ticket type. He doesn't want anyone redeeming these online so he doesn't give a redemption code. Now the box office agent can't checkout those tickets when the media guys arrive because we are always assuming there'll be a code for box office.

Thinking this over again if the promoter made the comps and didn't give the codes they are effectively private and we just need some means of checking in at the time of the box office. We have an issue for that feature which was one of the scenarios Zach (IIRC) mentioned when we added comps https://github.com/big-neon/bn-api/issues/480

**Comment by mikethetike** [comment]
Good point. I can't think of any places where the `is_private` would be used. Basically the UI would show the redemption code as Optional with some indication that if it is not supplied, then it is reserved but not redeemable (except via Box Office).

**Comment by Timo614** [comment]
> We would still need to store an actual redemption code in the DB though, but somehow know not to display this in the UI. I think this is what I was thinking of using the `is_private` flag for

Yeah after I took a quick look I realized we only show the hold redemption codes to the admins in the tooling itself. So there wouldn't be anyone to really hide it from in the UI. I guess if we planned on automatically emailing the redemption code to the user if email was provided then it could be a problem. We may want to have some flag about whether to send an email though in that case on the hold itself. 

With #480 we should be able to handle that case that @Jasonvdb mentioned as it should introduce a means to lookup a user by name, find their comp, and make their purchase. Redemption code would still be used we just would prevent the user from ever finding out.

I do see some value in the null redemption_codes setup though thinking over one case that's likely to come up. There could be a fixed inventory of held tickets that an organization wishes to pre-allocate as one big hold they'd then split off into other holds, comps, etc. Without the null redemption codes approach there's a useless redemption code that organizations never want used. Since I did the work to support it before I'll rebase it over the current master, quickly confirm its set, and push up a PR for at least supporting that.
