### ISSUE TITLE
If an name is assigned to a discount holds list, the type and discount should be inherited from the parent

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#1065]
hold_type
discount_in_cents
end_at
hold_type
max_per_order

**Comment by Timo614** [comment]
Just confirming this is for when you're splitting an existing hold?

![screen shot 2019-02-26 at 3 31 59 pm](https://user-images.githubusercontent.com/1319304/53444327-db37d080-39db-11e9-916c-1b329928c21b.png)

From the looks of the tooling it looks like it defaults to the existing type and discount. So if you have a discount type with $11 discounted and go to split it it'll be defaulted to Discount and $11 off. 

Wondering if this issue was to remove the option altogether to force splits along the same type? So no Comps made from Discount etc? Or is this for some other issue?

**Comment by Timo614** [comment]
Actually I see where this logic is involved. So this is where you click the hold directly and can add names there. It seems like right now even if it's a discount type it'll make comps. Sounds good will adjust that.

**Comment by Timo614** [comment]
@Jasonvdb after taking a look here it looks like bn-web calls the comp endpoint directly. So it's requesting a comp there for each of the items on that list.

https://github.com/big-neon/bn-web/blob/6e1c762387d99349b1b8eaa21e7abf857dc18514/src/components/pages/admin/events/dashboard/comps/List.js

So the goal here would be to allow both right?

Thinking things over and reviewing the code a bit I realized why that's currently set to comps specifically. Originally I believe holds were set to be associated with individual users via lists like this just the comps so likely we just filtered on it that way and set up the logic to work around that.

@mikethetike I wonder if it'd be worth removing the notion of comps at some point. Still having the type to designate if it's 100% free and has no fees but otherwise having the tooling combine them. Instead of having them be treated like a separate entity for the endpoints they'd just be a type set on the hold itself with some optional fields for name etc.

It sounds like for this issue I'll need to:

- Add a new holds endpoint that takes the same fields as the comps create for a comp but instead splits it based on the current type to a new hold with the same type and discount
- Add a new endpoint to return the full list of holds who are children to a given hold (since some may not be comps can't use its index)

**Comment by Jasonvdb** [comment]
Oh ok I see I'm posting to a comps endpoint there but expected the child of a discount to also be a discount. Think the proposed solution you have there sounds good. 

@mikethetike @Krakaw ?

**Comment by mikethetike** [comment]
@Timo614 Yeah, it's mainly a convenience method to create them. Originally (and currently) the UI only allows for creating a comp from a hold, but it looks like we will be making use of holds that are children of holds. E.g. I've reserved 100 tickets for media and I have 3 employees who all have access to distribute them. If one of them splits out 20 tickets for someone and then wants to put them back, they should go back to the original hold. 

Not sure how the UI will look, but there seems to be two operations here:
1. Splitting the original 100 into a sub hold of 20 where they will be returned to the parent 100 if released
2. Splitting the 20 into 15 and 5. If released they should go back to the 100, not the 20
