### ISSUE TITLE
Org Management - Unable to create venue

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#1088]
![image](https://user-images.githubusercontent.com/456953/53623609-4ebd2600-3c06-11e9-8e13-fe5f215ad5db.png)

**Comment by Timo614** [comment]
Looks like the `region_id` is required now but it's not returning a validation so when it's missing its erroring out. Will add a validation field for that.

**Comment by Timo614** [comment]
Looks like the `region_id` is required now but it's not returning a validation so when it's missing its erroring out.

Since this error is happening as part of deserialization it's an issue with bn-web where we need to just mark the field as required / pass it along to the API with some selection. It's currently blowing up in serde's logic during actix-web deserialization. 

Was made required with #681 previously the `region_id` field was optional.

**Comment by Timo614** [comment]
@Jasonvdb just a heads up this one ended up being just that we made the `region_id` required so need to force it from bn-web.

**Comment by Jasonvdb** [comment]
Thanks yeah it's in https://github.com/big-neon/bn-web/pull/1172

**Comment by Krakaw** [comment]
This was closed in big-neon/bn-web#1172
