### ISSUE TITLE
Refunds - Improve Data model

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#1253]
The current refund model makes it difficult to generate an email or report on a single refund that occurs. E.g. if there are two refunds on an order, it is difficult to separate which happened at which time without using DomainEvents. 

I suggest we make a data model similar to this:

```

   +-------------+
   |  Orders     |                           +------------------------+
   |             |                           | Payments               |
   |  - id       |   +----------------+      | * id                   |
   |             |   | Refunds        |      | * order_id             |
   +-------------+   | * id           |      | * refund_id (nullable) |
                     | * order_id     |      |                        |
                     | * created_by   |      +------------------------+
                     |                |
                     +----------------+



                        +----------------------------+
                        | RefundItem                 |
                        | * refund_id                |
                        | * order_item_id (nullable) |
                        | * quantity                 |
                        | * amount                   |
                        |                            |
                        +----------------------------+





```

**Comment by Timo614** [comment]
If we plan on having the frontend stay mostly the same we need to still support the existing `RefundedTicket` items as they keep track of which tickets have been refunded and their fees which was one of the requirements. We could switch to this setup but it may make things a bit more arbitrary in terms of which tickets are refunded.

One thing we could do though is instead of listing `fee_refunded_at` and `ticket_refunded_at` we could instead link back to the `fee_refund_item_id` and `ticket_refund_item_id` and store them all as part of the same refund. The RefundItem records would have a 1 -> m relation for the the RefundedTicket records but otherwise things would mostly stay the same. This would just add some additional reporting logic we could use to generate the email more easily then but not change the nature of how the refunds are processed (on a per ticket level with the option to refund just the fee, etc.).
