### ISSUE TITLE
Ticket Transfers - Reminder drip notifications

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1300]
Connected to: https://github.com/big-neon/bigneon/issues/148

**Context/Problem:** If a user doesn't accept their ticket transfer there can be issues the night of the event scrambling to sort it out at the door. A transferrer may mistakenly send a ticket to the wrong address and not realize the intended transferee didn't receive the transfer. 

**Hypothesis:** By sending reminders to both parties until the transfer is accepted/cancelled we will reduce friction at the door/night of event and reduce the likelihood of customer support having to track down ticket transfers

A **transferrer** should receive notifications letting them know their transfer has not yet been accepted, including the transfer details, instructing them to remind their friend or cancel and resend the transfer

A **transferee** should receive a series of time based notifications reminding them to accept their ticket transfer

> The cadence is still in discussion so if you can set this up to be flexible that'd be great. The frequency should actually accelerate as the event approaches... T -0, T -1, T -3, T -7 etc. So when you set up the logic it should be based on the date/time of show

**Comment by nine-tari** [comment]
This may be hard to QA but I think we'll be adding the ability to use minutes instead of days prior to the event start to help with that so should be easier once it's in place. I put this in review now since the logic is there and would work just could take days to see them appear depending upon the event start dates set.

If the script was not run in develop or beta older events may not get these drips.

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected. Both the parties received notification emails that the transferred tickets haven't been claimed yet.

**Comment by Anziskavds** [comment]
Tested on Prod and is working as expected.
