### ISSUE TITLE
Staging environment modifications for drip delivery

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1346]
It was mentioned that it's difficult to test the drip behavior as the drips fire based upon the distance from the event start. In order to allow develop and beta testing to be made easier it has been asked that we use minutes from the event instead of days to trigger the emails.

I made this a priority as it would be otherwise rather difficult for QA to test the transfer drips in those environments.

**Comment by nine-tari** [comment]
This was merged while I was out so pushing to the review pile. It changed the behavior in the staging environment (assuming that environment is setup as staging / was one of the release tasks) to have the drips be sent at minute intervals instead of days. So if it was going to be sent 7 days prior it now sends it 7 minutes prior in those environments and then sets up the next to be sent 1 minute prior. Was requested in the mattermost chat a bit back to make testing the drips easier / not having to wait around for days to check behavior like that in the testing environments.

Worth confirming with KS or Mike prior to checking that the env is set as staging.

**Comment by Anziskavds** [comment]
Tested successful on Prod
