### ISSUE TITLE
New endpoint for resending an order confirmation email

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#1390]
Required for order management:
![Screenshot 2019-07-09 at 14.46.24.png]
(https://images.zenhubusercontent.com/5ce2547f6eb508477b329ac7/6728adc1-e70a-4180-a0a5-cd3166937e77)

**Comment by nine-tari** [comment]
Should this order confirmation take into account refunds since? Or just show the order as it was at the time of purchase like it was set in stone?

Just confirming if we want it to only show items still currently associated if we refund the event fee etc.

**Comment by Timo614** [comment]
Also what permissions should be able to trigger this? Anyone who has the ability to read the order?

**Comment by Jasonvdb** [comment]
Yeah thanks same permission as the reading an order should be fine. 

My guess would be the resend should only show the items that haven't been refunded. @Tas4tari @harrisonlemon what do you guys think?

**Comment by Tas4tari** [comment]
I think you're right but lets just double check this with @harrisonlemon

**Comment by harrisonlemon** [comment]
Hi @Jasonvdb @Tas4tari The order confirmation should mirror the current order state, itemizing paid and refunded inventory if applicable.

Sample Tfly confirmation here:
![Image Pasted at 2019-7-19 08-33](https://user-images.githubusercontent.com/49532549/61547325-c6062180-aa10-11e9-8372-76d573208051.png)

**Comment by Timo614** [comment]
I noticed while going through this that the discounts (that aren't inclusive / promo codes) are currently being rolled up into the fees for the email.

I'm making adjustments so it matches the order view as well here in this associated branch.

Current:
![Screen Shot 2019-07-22 at 11 26 09 AM](https://user-images.githubusercontent.com/1319304/61644899-96a31f00-ac73-11e9-8e82-d79da02cbd5f.png)

Order view for this order:
![Screen Shot 2019-07-22 at 11 26 14 AM](https://user-images.githubusercontent.com/1319304/61644900-96a31f00-ac73-11e9-8a06-17c2d82c8815.png)

**Comment by Timo614** [comment]
I did some experiments / testing to make sure things looked okay with the discount. Let me know if this looks okay or if we want to modify it somehow. I added the discount breakdown (fixing the above issue I mentioned) and also added support for refunds.

Some notes: 
- I wasn't sure if we wanted the discount to be red or black since it is removing part of the cost but still part of the initial ticket price
- I also added a new table sendgrid template for the fees breakdown to show the refund taken out of the fees total there. I can't switch it for the production template used here because it'll be empty until it goes live but I fetched it below (first example). Currently the service fees in the email reflects the refunded amount out of the total we'll just need to later update the template once the PR is live to show the breakdown in the same way.

```
"total_breakdown":"<table><tbody><tr><th>Fees Total</th><td>1.50</td></tr><tr style=\"color: red\"><th>Refunded</th><td>($0.20)</td></tr><tr><th>Order Total</th><td>90.30</td></tr></tbody></table>",
```


Buying 3 non discount, 2 with discount:
![Screen Shot 2019-07-22 at 1 20 52 PM](https://user-images.githubusercontent.com/1319304/61654320-2b187c00-ac8a-11e9-97b4-2f4f15b9d3e9.png)

Relevant part of order confirmation email:
![Screen Shot 2019-07-22 at 1 23 23 PM](https://user-images.githubusercontent.com/1319304/61654324-2bb11280-ac8a-11e9-8299-3d1024bec10d.png)

Order history page:
![Screen Shot 2019-07-22 at 1 21 27 PM](https://user-images.githubusercontent.com/1319304/61654321-2bb11280-ac8a-11e9-9dc6-af22841e0d0a.png)

Refunding one of each (discount and non discount):
![Screen Shot 2019-07-22 at 1 21 48 PM](https://user-images.githubusercontent.com/1319304/61654322-2bb11280-ac8a-11e9-9488-158177c4bea3.png)
![Screen Shot 2019-07-22 at 1 21 56 PM](https://user-images.githubusercontent.com/1319304/61654323-2bb11280-ac8a-11e9-81cc-31c3c57551b8.png)

Relevant part of order confirmation (note refunded items now):
![Screen Shot 2019-07-22 at 1 24 20 PM](https://user-images.githubusercontent.com/1319304/61654325-2bb11280-ac8a-11e9-8b0c-297d20c582c1.png)

Order confirmation (filed: https://github.com/big-neon/bn-web/issues/1633 for the bugs here: the display as the fee isn't reflecting the 0.20 off, no refunds listed, and discount is out of order with the items involved so not directly under it's parent order item):
![Screen Shot 2019-07-22 at 2 13 42 PM](https://user-images.githubusercontent.com/1319304/61654673-f48f3100-ac8a-11e9-9b25-b76c7b95e4c0.png)
