### ISSUE TITLE
Fan Management: Add Search to Fans list 

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-api#1430]
User should be able to search the Fans list for a specific user. https://develop.bigneon.com/admin/fans

User should be able to search by FirstName, Surname, FirstName and Surname, email address
References #1429

**Comment by Anziskavds** [comment]
Tested on develop and it is not working as expected. It doesn't give you the specific name you typed in and when you clear the search bar the fans page doesn't reload, it stays on the page it gave you when you tried to search for something. https://cl.ly/e82b1fde2fb9

**Comment by Timo614** [comment]
It looks like those issues appear to be issues with the UI -- I'll file some new issues there and link here. One appears to be just a general search issue with how it's handling search and the other is an issue with big data sets and how it's rendering results / loading.

It is using a fuzzy search now so there will be additional results returned if there's a partial letter match across a full name but these don't appear to be that.

I used the organization you had open in the screenshot and when I do the search it looks like it's working:
![Screen Shot 2019-08-02 at 10 41 12 AM](https://user-images.githubusercontent.com/1319304/62378430-d212d880-b512-11e9-9c28-4caf4f9c2b4f.png)
![Screen Shot 2019-08-02 at 10 41 31 AM](https://user-images.githubusercontent.com/1319304/62378431-d212d880-b512-11e9-85d3-fb2ab15f4657.png)

One of the bugs you mentioned was how it didn't show the full result set after removing the query. If you wait a bit after removing the query it will load it's just really slow. If you type in a new query it quickly loads the query results but then the results from removing the query before come in and it renders them. It's the same behavior with the pagination it'll load just really slowly. If we had some sort of loading overlay perhaps it would be beneficial there.

Causes the behaviors seen:
- Not rendering the empty search result set
- Pagination appearing to not function
- Page resets after search (if you search for something, remove the search query, and then search for something else it'll render the something else and then immediately render the empty result set as it finishes its render logic after the new search)

Another bug is the results page mentioning no results for the keywords. This appears to be a UI bug with how the search works. It should likely always use page 1 for the results but it's currently using the same page as you're on. So what happens is when you're on page 2 (like in the example) it goes and returns a generic no records found since there's no page 2 of the results to render. If you're on page 1 (like I was above) then it renders it as it uses that page.

**Comment by Anziskavds** [comment]
Tested on develop and beta and seems to be working as expected. Also tested on Prod but I'm unable to search for the last name first and then the first name but I can search with the last name first and first name second on develop and beta.

**Comment by Anziskavds** [comment]
Tested unsuccessful on Prod.

**Comment by Anziskavds** [comment]
@Timo614 @harrisonlemon Should it be possible to search with the last name first and the first name second?

**Comment by harrisonlemon** [comment]
@Anziskavds and @Timo614  Yes, a user should be able to search by:

- [First Name]

- [Last Name]

- [First Name] [Last Name]

- [email address]

- [phone number]

Searching by [last name] [first name] is not necessary. Thanks!

**Comment by Anziskavds** [comment]
Tested successful on Develop and Beta for web and mobile web but unsuccessful on Prod. I am unable to search by any of the following on Prod:

[First Name]

[Last Name]

[First Name][Last Name]

[email address]

[phone number]

I received "No fans currently"

**Comment by Krakaw** [comment]
@Anziskavds Please add the versions you tested with in the comment. You can paste the image from beta / prod like this: 
![image](https://user-images.githubusercontent.com/41575888/62602977-3956d100-b8f5-11e9-891a-ae93e87f56a2.png)

Press `cmd + ctrl + shift + 4` then select the version block and press `cmd + v` in the github comment to paste the image.

**Comment by Anziskavds** [comment]
Tested successful on Develop and Beta for web and mobile web but unsuccessful on Prod. I am unable to search by any of the following on Prod:

[First Name]

[Last Name]

[First Name][Last Name]

[email address]

[phone number]

I received "No fans currently"

Prod:
![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/738284fd-ec40-44fb-baa9-1757f3378518)

**Comment by Timo614** [comment]
When you tested on production did you happen to be on a page other than 1 when you did the search? 

It may be that other bug we have mentioned somewhere where search uses the page you're on when it searches. So if there's only 1 page of search results for a term and you do the search from a page 2 of your current query it returns no results because there's nothing to return for page 2. 

If you do a search for "qa test" via https://develop.bigneon.com/admin/fans on the 4000 tix org it returns one page of results. If you visit https://develop.bigneon.com/admin/fans?page=2 instead with no search query and then do a search for "qa test" it returns that there are no fans currently.

**Comment by Anziskavds** [comment]
Retested on Prod and is working as expected.
