### ISSUE TITLE
cancelled_at added to /events as a query param

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#270]
Filtering in bn-web now but would be better to have a param for this. Something like `status=cancelled/live/all`.

Showing results to users that hit the front page will need to ignore cancelled events but admins might still want to see them in their list.

**Comment by Timo614** [comment]
Adding this -- the event statuses we have now are: `Draft,Closed,Published,Offline`.

So for "Live" you want it to include `Published` and `Offline`?
For "Cancelled" you want it to include `Closed`?
For all since the field is optional we just won't include the filter in that case.

Have it working that way now -- let me know if you need any modifications on that front or if that was what you were thinking by the statuses.

**Comment by Jasonvdb** [comment]
If I'm displaying all live events on the front page would that not exclude `Offline`? Unless I'm not sure what the `Offline` is used for?

If you prefer to keep it simple, using the status param matching the DB as one of `Draft,Closed,Published,Offline` I can use it that way. I was just giving an example of something like what the frontend would need but it's flexible.
