### ISSUE TITLE
Create API to view Ticket Types and the current price point

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#293]

**Comment by Timo614** [comment]
@mikethetike Just noticed we may already have this via #217: 
https://github.com/big-neon/bn-api/blob/cd11cfe79ef2a9c5dc0436874eed8700cd1e8859/api/src/routing.rs#L35
https://github.com/big-neon/bn-api/blob/cd11cfe79ef2a9c5dc0436874eed8700cd1e8859/api/src/controllers/events.rs#L401

Looks like it uses the ticket_pricing call to fetch the current price point:
https://github.com/big-neon/bn-api/blob/cd11cfe79ef2a9c5dc0436874eed8700cd1e8859/api/src/models/display_ticket_type.rs#L21
https://github.com/big-neon/bn-api/blob/cd11cfe79ef2a9c5dc0436874eed8700cd1e8859/db/src/models/ticket_types.rs#L55

Or is this card for something else? Just confirming since I think we have what the subject covers via 217's logic there.

**Comment by Timo614** [comment]
Or is this to add a `GET` request and `show` action for the ticket types for the purposes of hitting an endpoint for an individual ticket type for its current values by id? Can add that if so just confirming.

**Comment by Jasonvdb** [comment]
This endpoint can work but bn-web needs to know which current price should be used to display to the user. So this can probably be solved by just adding the `current_price` or something to each ticket type?

**Comment by mikethetike** [comment]
I think there may need to be two endpoints here. The one is for the user to see, the other is for the org members to see when editing it. 
Currently, `/events/{id}/tickets` returns what is needed for the org members. It should actually be restricted as such.

I think we can perhaps add the tickets_types to the `/events/{id}` public method. In that case I suggest we show the ticket types with a single price

**Comment by Jasonvdb** [comment]
Cool agreed
