### ISSUE TITLE
Add current ticket pricing to `/events/{id}`

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#309]
Need to know which price points are active for which ticket types to display on the events page.

Right now using `/events/{id}/tickets/` but that doesn't tell me which ticket price is the current one.

**Comment by Jasonvdb** [comment]
Also. Add status of ticket type if no ticket prices are in range or are sold out.

**Comment by Timo614** [comment]
Does it make sense to also return the number of tickets remaining? Since even if it's not sold out they may only have a few remaining so you're likely to run into an error if you try to reserve greater than that.

The remaining tickets value will likely change as reserved tickets are released and people edit their carts removing tickets freeing them up so thinking maybe the best call here is to fetch the number of remaining tickets for that type from the db and return that but if it's at 0 override the normal status of `TicketTypeStatus::Published` to return `TicketTypeStatus::SoldOut`. Then as soon as more open up it'll just go back to the published state. Does that make sense here?

It would force us to do an extra query against the database each time we want to call this but not sure of a better way to figure out that x number of tickets are left. To optimize it a bit when we go to sell the tickets we could have the logic check if there are any remaining unsold tickets (reserved or not) and update accordingly to the `TicketTypeStatus::SoldOut` to avoid the extra query for ones that have none remaining.

Was thinking of something similar for the ticket prices -- for the range you're saying if they'd be active at the time the user was calling the API right? So if they don't currently have an active ticket price then returning `TicketTypeStatus::NoActivePricing` or something along those lines?

Handling this one along with the changes to #293 mentioned by Mike to lockdown that endpoint to just the organization in one pull request.

**Comment by mikethetike** [comment]
> Does it make sense to also return the number of tickets remaining?  

Yes, although this might need to be obsfucated at a later stage (e.g. "<1000")

> Just confirming by sold out we mean there are currently no unreserved tickets remaining

Sold out means there are no tickets available for you to buy right now. It may be that it becomes unsold out later. So yes.

>extra query against the database each time we want to call this

Unfortunately, yes. We could risk caching this maybe next year some time, but that could lead to a very bad user experience when we get it wrong. I like the idea of updating the status though because for sold out events, they are total sold out. _However_, if the ticket status is "SoldOut", then is there ever going to be a check to see if reservations on tickets have expired?

> TicketTypeStatus::NoActivePricing

This is fine, it should show "Not available (yet?)" on the front end.
