### ISSUE TITLE
Validate before posting that no 2 date periods overlap for prices

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#311]
When adding a ticket to cart, if we 2 ticket pricings in the `get_current_ticket_pricing` function because of overlapping dates, then the user can't buy a ticket.

Will implement validating in bn-web which will solve the problem for now but should also be validated in the backend.

**Comment by Timo614** [comment]
I originally was approaching this from the angle of using the validator crate in addition to some db level checks on this but thinking it over now I'm wondering if using check constraints and triggers to accomplish some of these validations would make more sense here. I'd think diesel should still mention the trigger that's causing it to fail and since we're using client side validation to prevent it as well that plus the trigger should be enough to handle this.

I'll attach the code I was working on here in case there's some value in the future / if the trigger approach doesn't work out but I think that approach is going to be a lot cleaner. Will have to see what sort of response diesel gives in that case.

https://github.com/big-neon/bn-api/commit/844c6a491723473277fc697b3934bc95d7d55596

**Comment by mikethetike** [comment]
It'll probably need to be a trigger unless check constraints can look at multiple rows on postgres. We must just be careful about using triggers on performance critical upsert tables (which these are not), otherwise it could be tricky to debug perf problems. 

Happy otherwise
