### ISSUE TITLE
Enable updating of ticket type capacity

### ISSUE THREAD

**Issue by neonknight64** [big-neon/bn-api#320]
The update_tickets event controller needs to be improved to allow the changing of ticket capacity. 

If the new capacity is less -> mark some of the existing ticket instances as unusable
If the new capacity is more -> reuse previously marked unusable tickets and issue more ticket instances if needed

**Comment by Timo614** [comment]
How are we going to determine which ticket instances to mark as unusable? Just select any of the unassigned?

I imagine since these link back to assets if we're removing capacity that probably means we either plan on using the asset for a different ticket or we need to remove specific assets right? Or are we just going to sideline these specifics assets and not have them associated with a ticket any more regardless? Unless I'm misunderstanding how that'll work in practice.

**Comment by Krakaw** [comment]
Duplicate of #146
