### ISSUE TITLE
events.ticket_types endpoint should return the associated fee per ticket for each ticketType

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#416]

**Comment by Timo614** [comment]
Will grab this one. 

Just confirming: since the fee schedules are organization based the best approach here is to just return two extra fields on the event object right? One for the `EventFee` (if one exists) and one for the per unit fee? Or is this part of some per ticket type fee we're going to add in a different card / this card? Just confirming before I jump in but sounds good.

**Comment by zmelamed** [comment]
The per unit fee can be different from ticket to ticket based on the price and where it falls on the orgs fee schedule. So 1) yes the event fee should be returned with the event object. 2) the ticket types themselves need to have a specific fee associated with each based on their price and where it lands on that organizations fee schedule
