### ISSUE TITLE
Make add to cart accept array of ticket types

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#434]
When adding multiple tickets to cart in bn-web it's firing off multiple requests at once. If there's no existing cart this causes multiple carts to get created when the calls happen simultaneously. Then only one cart is returned to the user and it looks like the other selected tickets were not added.

Doing one API call with an array with the same structure of `AddToCartRequest` would solve this.

**Comment by Timo614** [comment]
We may want to keep this issue alive and handle the case where multiple requests are sent in tandem somehow in addition to allowing them to be added in one call (which I did in the associated PR). Otherwise we'll end up with a lot of orphan carts if people spam the add to cart logic triggering a race condition (what do you think @mikethetike ?).
