### ISSUE TITLE
Return validation error for when ticket types overlap

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#519]
Currently if ticket type dates overlap, the web receives this packet: 
```json
{"error":"Could not insert record"}
```

in the logs, this is caused by:
```json
{ "level": "DEBUG", "target": "actix_web::pipeline", "message": "BigNeonError(DatabaseError { code: 3100, message: "Could not insert record", cause: Some("Could not create ticket pricing, new row for relation \"ticket_pricing\" violates check constraint \"ticket_pricing_start_date_prior_to_end_date\""), error_code: InsertError })
```

The returned error should be a validation error with the correct fields marked

**Comment by Timo614** [comment]
This one is related to the start date needing to come before the end date check constraint. Adding a validation for that check constraint now. Going to make it generic and update other models currently not validating this to use the same validation / check constraint setup.

The overlap one has a validation it just runs after the creation / editing of the ticket prices:

Create:
https://github.com/big-neon/bn-api/blob/master/api/src/controllers/ticket_types.rs#L88
https://github.com/big-neon/bn-api/blob/master/api/src/controllers/ticket_types.rs#L100

Update:
https://github.com/big-neon/bn-api/blob/master/api/src/controllers/ticket_types.rs#L252
https://github.com/big-neon/bn-api/blob/master/api/src/controllers/ticket_types.rs#L315

Then the validation as part of the ticket type validation:
https://github.com/big-neon/bn-api/blob/master/db/src/models/ticket_types.rs#L110

It then triggers a rollback with the middleware if the validation fails via the middleware rollback logic.

Had to end up doing it that way as the endpoint takes a list of ticket pricing entries and otherwise there was no way to check they were valid for not overlapping until after they had already all been updated. The ordering could cause it to fail if the start dates intersected on the updated record prior to another one updating etc.

Will confirm that validation logic is still running once I have one in place for this other check constraint. 

https://github.com/big-neon/bn-api/pull/425
