### ISSUE TITLE
Add OrgOwner role when a user is set as the owner of new organization

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#64]
When creating an organization on the frontend and assigning an user as the owner, that user user needs to have the OrgOwner role added.

**Comment by Timo614** [comment]
I wonder if it's worth just doing a SQL query for some of these roles like org owner and org member at the time we're fetching them from the DB as they are dynamic depending upon the state of the other tables. For admin I think it makes sense to store that but I'm wondering if we're just going to create a headache for ourselves by trying to keep this cache (since it's determined based on their state in their other tables) always up to date.

Otherwise when transferring ownership we have to be careful to always keep the cache across users up to date.

We already have to hit the db to determine the roles as otherwise the access token may not have the most up to date information so it's just another query at that time and it's looking up by the user_id so it should be pretty quick given how few organizations the system will have and the index.

It's not the end of the world if we want to cache it but I wonder if by doing so we're just headaches for ourselves by prematurely optimizing this. The alternative is when we update an organization to have a new owner we need to make sure to check if the existing owner had any other organizations (so they should keep the role) or if we should remove it from them and if the new owner already has the role or if we should add it for them. I can't imagine we'll have too many paths to set an organization owner. Organization member may require a few locations though as setting the org owner likely should give org member status and remove it from the other and so should the path to add a member to an organization.

I'm just wondering if we're prematurely optimizing a bit by trying to cache these dynamic roles. We could do something with a view that determines the roles in addition and appends them that should be added though if we want middle ground with a cache still. Still may be a bit of premature optimization so not sure if that's worth it.

Not sure, what do you all think?

**Comment by Jasonvdb** [comment]
At the moment in bn-web the roles are not being cached at all. They were when they were stored in the token.

Right now I'm loading in user details & roles from `/users/me` every time the web app gets loaded and then again every 5min if the tab is still open. So if a user's roles gets updated, they could just refresh the page to get the latest roles right away.

Guess this will change if we're going ahead and doing the scopes thing but I needed a way to use roles in the meantime so that's why @mikethetike added it to the api for me.

**Comment by Timo614** [comment]
I meant we're technically caching the OrgOwner and OrgMember by storing them in the users table role field since they are dynamically determined. Was thinking one option could be to use a db view to append any dynamic role to the user's existing static roles list (like Admin which isn't determined based on any other table data). 

Otherwise we have to handle adding and removing the roles whenever we alter a user's org membership in some way. It's not the end of the world if we choose to do that just was thinking the other approach would be cleaner as we don't have to pepper the code with adding and removing roles and handling their edge cases (I mentioned a few above like org owners having two orgs and then transferring one). The view approach would be somewhat of a middle ground giving us the dynamic roles still cached in the view but remove the need to manually add and remove roles associated with them.

**Comment by philipr-za** [comment]
Resolved in https://github.com/big-neon/bn-api/pull/127
