### ISSUE TITLE
Add OrderNumber as field when returning an order

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#654]

**Comment by Timo614** [comment]
@mikethetike what's order number here? 

- The user's current order number in relation to the orders they have made on the system? 
- The number in relation to the organizations total purchased orders (via events)? 
- Or some additional auto incrementing field we're going to track as opposed to the UUID we use for the id now?

Guessing the first but confirming. I vaguely recall the UUID ids being used instead of a number to somewhat mask how many orders the system had made from the user (although perhaps I'm misremembering).

**Comment by mikethetike** [comment]
In a lot of places on the front end we take the last 6 or so digits, but it's always done on the front end.  I think this should be done uniformly on the backend:
![image](https://user-images.githubusercontent.com/4200336/49577458-1a600380-f950-11e8-881f-2db2a2f46410.png)

**Comment by Timo614** [comment]
Going to base the order number size off of the included mockup. Let me know if we want to adjust how many characters later (will be dynamic so we can adjust if we want to make it display less/more than 8).
