### ISSUE TITLE
Org Owner can't create artist

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#660]
To reproduce:

1. Create Org as Admin
2. Log in as OrgOwner
3. Start creating event. 
4. Type in "New Artist Name" as headlining act, click "Create new artist..."

Get "User does not have permission"

**Comment by Timo614** [comment]
Hmm we have a functional tests that checks that role's ability to add artists so should be working unless the test has some flawed logic. 

Will have to dig in but my guess is the endpoint call probably is missing the `organization_id` for the artist create method so it's trying to create a public artist (which is only allowed by admins) instead of a private organization one (which can be toggled to public by admins).

It functions very similarly to the Venue.

https://github.com/big-neon/bn-web/blob/5f9d824b81cf33c0716f55b0cf6fd8f1b88d91b6/src/components/pages/admin/venues/Venue.js#L262

https://github.com/big-neon/bn-web/blob/5f9d824b81cf33c0716f55b0cf6fd8f1b88d91b6/src/components/pages/admin/artists/Artist.js#L170

I don't think bn-web is passing it in with this case from the looks of the associated repo so may just need to be modified there.

**Comment by SWvheerden** [comment]
Unit test tests for false

**Comment by mikethetike** [comment]
The problem is actually that the front end is not passing the org_id in. I think @Jasonvdb might have made a fix for this already
