### ISSUE TITLE
Use google place ID to check if a venue exists already.

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#74]
Frontend is using Google places API already and passing through `place_id` param to `/venues`.

This field can be used to determine when to add a new venue.

**Comment by Timo614** [comment]
Just confirming but for this card we want to:

1. Store `place_id` that's being passed in to the venues table.
2. Do a search for `place_id` when a venue is being created and if it exists already return that venue instead of creating a new venue? So return status 200 (ok) instead of 201 (created) if we see the venue already exists?

Is `place_id` something that will always be passed in so something we should require on the venues table?

I'll grab this card but will hold off on implementing anything for now pending that clarification.

**Comment by Krakaw** [comment]
google_place_id is being stored
