### ISSUE TITLE
There are many (Incorrect) logs for "Unauthorized Access attempt" for this url

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#781]
In data dog.
Identified on Production

accessed_scope:org:admin
global_scopes: event:interest, order:read, ticket:transfer
url: /organizations

**Comment by Timo614** [comment]
Relates to https://github.com/big-neon/bn-api/blob/master/api/src/controllers/organizations.rs#L57 since it's checking requires_scope and then branching off if it's an ok result. The requires scope call triggers logging related to unauthorized access attempts so we likely just need to have a method call that doesn't trigger logging it uses instead.
