### ISSUE TITLE
Event Management - Ticket Type Deletion - Deleting a ticket type should remove unsold tickets from the total event capacity, reports and all dashboard views.

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#881]
Right now deleting a ticket type marks it as cancelled, but the total qty still shows up in the total capacity stats, reports and the ticket type inventory levels card still shows up in the various dashboard views

- If a ticket type is deleted, and no tickets had yet been sold from that ticket type, it should be completely hidden from the interfaces and reports
- If a ticket type is deleted, but tickets had been sold, the reports should only show the sold inventory stats, and the unsold ticket counts should not be included anywhere

**Comment by Timo614** [comment]
So if we're cancelling these we want to `nullify` the tickets and on the blockchain similar to when we lower the capacity of a ticket type right? I noticed when I took a quick look that we only nullify available tickets. 

How do we want the logic to behave in the event some of these tickets are in the cart at the time of cancelling? They would become available again as soon as the reservation ended so they could end up back in inventory again.

For the partial payments logic where a partial payment can reserve tickets for up to a day would we want to trigger a refund on any partially paid orders if we plan on removing them above? Wondering how the cart would show this to the user.

One idea could be to mark the tickets as nullified and then have the cart fail to checkout if it's attempted. Perhaps having some additional text in the cart show logic to include a flag that the order cannot be purchased with some information as to why and the individual order items that need to be remove marked? The same sort of issue occurs if codes are no longer in their active period (we have start and end dates for discount codes) and the user wants to checkout. Perhaps we should have another issue to add some sort of invalidate cart messaging and flags to let the user know (thinking similar to how Amazon lets you know if a price has changed since you last added it to the cart but in this case that you can no longer purchase a given item).

**Comment by Timo614** [comment]
![screen shot 2019-01-17 at 4 18 29 pm](https://user-images.githubusercontent.com/1319304/51349500-94b59480-1a73-11e9-8aed-cd8776fbd161.png)

I adjusted the logic to nullify the available tickets. This graph shows an example of what's left for an actively sold one with holds. I had the logic recursively release the hold's tickets and set their effective quantity to the unsold count prior to nullifying the remaining inventory.

49 of the tickets were reserved and the 30 held were all already purchased (should we make an issue for that? double counting them in the sold and held figures held only checks if they have a `hold_id` and doesn't exclude ones in the `Purchased` or `Redeemed` state.

**Comment by Timo614** [comment]
@zmelamed I think it may actually be a bn-web issue -- looked into it and saw that the API returns two values one for how many are held and one for how many held are sold via `tickets_held` and `sold_held` so should be able to deduct the latter from the former on the dashboard to get the right value it's just using the former right now.
