### ISSUE TITLE
Each organization should be able to specify which payment methods to allow

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#937]
E.g. only certain orgs would want to use Globee

**Comment by Timo614** [comment]
One difficulty of this issue is that we allow tickets to be purchased from multiple organizations so they may get into a state where only some portion of an order can be paid for in each. 

@zmelamed how do we want this behavior to be handled? 

- Should we disallow tickets belonging to organizations which don't support at least some subset of the cart from being added as they'd be impossible to purchase in one go? So if organization A supports both and organization B only Stripe we allow it since they'd still be able to use Stripe just at checkout time can't use Globee? 
- Or should we track which order items we've paid for and force the user to go through two payment providers to purchase the entire cart if they do want to use Globee (may open the door to other oddities where the order is only half paid etc).

Wondering what we'd do in the latter case in the event one organization supported only Stripe while the other only Globee since they'd be unable to checkout. 

This may become a support issue with people being unaware as to why they can't use a certain provider for a portion of their tickets as well.

**Comment by Timo614** [comment]
@mikethetike  @zmelamed I believe it would cost more for the latter for now mostly because of the amount of bn-api, bn-web, and bn-api-node work related to making that shift and the questions it would introduce this late in the project. Probably will require some effort on the mobile app to make the switch as well given the need for messaging there.

To support individual carts we'd first have to decide whether or not to keep a cart around for each organization (scope it via the API under organizations) or update logic and messaging to inform users that they can't purchase until they clear their cart introducing new workflows. For the former it may be a weird experience for the user to have multiple carts in various states if they end up trying to add a second ticket to the cart from a different organization.

We'd also then have to add new validations related to locking down the cart to just those organization events and message to the users that they can't purchase other tickets until they've completed their current cart.

On the plus side: It would clean up some logic around displaying the user's cart as we no longer have to worry about there being other organization data in there for the purposes of redeeming tickets and displaying cart information though, it may make some logic easier to calculate though as we can think link an order directly to the organization_id, and it opens the door to more custom behavior around payment providers given the cart experience is customized to one given organization alone.

For this logic assuming Stripe / Credit Card is always active it should be pretty basic just limiting selection on payment providers in the event one of the tickets doesn't support Globee. I think as long as the credit card provider is never shut off we won't run into an issue there given there will always be a fallback option so we never need to split the cart payment into two providers. If we do ever support multiple payment providers like Stripe, Braintree, etc. for credit card it will become an issue again though.

Do the launch organizations care about restricting Globee? I wonder if it makes more sense to wait on this issue for now and circle back after we've done the initial launch. We could then spend some time breaking it apart. I do feel like if we launch with it supporting multiple organizations it's less likely we'll end up doing it later as it'll be a significant change to the workflows and be a lot harder to launch all at once given how much will need to be modified across the sites so it may end up limiting our payment provider selection unless we're up for a big breaking change with significant downtime and the need to coordinate updating API consumers across the board. So more of a cost today but limits us in the long run significantly to keep them in the same cart and likely will cost us a lot more later to make that change if we launch without it.

Not sure which is more ideal I feel like if we ever intend to make the switch to one cart per organization though now would be the best time to do it. Given the hold for these tickets isn't that long I doubt people will want to try to buy tickets from a bunch of events from various organizations as they'd worry that they may lose out on them by waiting too long so it may not even be an issue for the most part as you mentioned just a rare edge case we keep having to work around given the support of it now.

**Comment by Timo614** [comment]
Just was looking through the open PR list and I noticed Mike also has a branch for this he pushed a PR up for: https://github.com/big-neon/bn-api/pull/954 we can use that one for any modifications we need to make here, will reassign that way.

**Comment by mikethetike** [comment]
I created a basic PR for retrieving the available payment methods, only allowing the minimum  set that all the orgs in a cart allow. There are no API methods for updating this yet,so this has to be managed via the database. 

With regards to the "One org per cart" that should be fine because AFAIK both of the front ends use the Replace Cart method from an event page and not the PATCH method.

**Comment by mikethetike** [comment]
I'm going to unassign myself because the work that still needs to be done on this is creating the UPDATE API

**Comment by Timo614** [comment]
I'll handle the update API aspect here.

**Comment by philipr-za** [comment]
Woops, sorry Waffle didn't show the self-assign before I PR'ed this.
