### ISSUE TITLE
Reporting - Org Level - Box Office Sales Summary

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-api#944]
Used for: https://github.com/big-neon/bn-web/issues/759

The Box Office Sales Summary report is used to reconcile a box office shift. It is a record of each logged in box office operator transactions. The subtotals under each operator breakout totals for credit card, cash, and other methods of payment. The last part of the report shows the Grand Total for all sellers.

https://docs.google.com/spreadsheets/d/1n_cNbKFQ7NExPx42d5GYohwo2CxHWFUVAWgFoRCe8Vc/edit#gid=127880016

**Comment by Timo614** [comment]
@Jasonvdb for the operator how are the types of payments recorded?

Since these are box office orders they happen with an external payment usually right? How would we know if it was cash or credit? They don't go through the normal checkout using someone's credit card details for credit box office do they? Like assisted ordering? 

I have most of this set locally just trying to figure out the best way to break apart the orders by that type. If it is externally processed we may need to require additional metadata from the external checkout flow so that we find out the type of order that these were. (Unless I'm missing something?)

How would you determine voucher as well? Is that one where they use a comp code? Or is that just a box office payment with external checkout and we'll likely need that same way of marking them with metadata to break them apart that way.

**Comment by Jasonvdb** [comment]
Yeah I see, @Krakaw @zmelamed what do you guys think?

**Comment by Timo614** [comment]
If we're currently just using the external method for all the orders (and these are designations from the type at the venue itself) I could add a simple required field to the external checkout to specify the type and then just use that to specify as per the chart. 

Wasn't sure if we were using the credit card checkout flow for box office though I guess it would work. If that's the case could just check the payment types the orders had just wasn't sure how that would all work in practice and if 'external' was another way of designating 'cash.'

**Comment by mikethetike** [comment]
@Timo614, yeah it's actually an oversight. We should pass through either cash or credit and store it. Either way it doesn't go through our payment processing, and fees are not applied.

**Comment by Timo614** [comment]
Sounds good I'll alter the branch to require a new field during external checkout and adjust the branch to use that for the report.
