### ISSUE TITLE
Org Roles - An org admin should be able to limit the access of any team member to a list of specific events

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#951]
An org admin should be able to "Restrict Access By Event" for a user by multi-selecting events that the user should have access to.

- Users who have limited access should not be able to access any section of studio for that org except for the list of events (which should only list events they have access to), and their related events dashboards and reports/tools/holds

**Comment by Timo614** [comment]
Sounds good, planning on having this work by introducing a new role for these EventAccessLimited users which grants them whatever associated scopes are related to the actions mentioned above. Will have the endpoint which returns the user roles by organization also return a list of event ids for these users and will adjust the logic to set roles to optionally take that event ids list as well.

**Comment by Timo614** [comment]
What functionality in the event dashboard should they have access to? Can they edit and cancel events? Can they refund tickets for that specific event?

Going to approach this at the moment as they should have full access to everything in the dashboard available for a given event but only the events they have associated with their user.

**Comment by Timo614** [comment]
Actually to avoid a lot of extra work we toss I'll push up what I have and take care of some of the current sprint ones in the meantime while we sort out the full functionality they should have.

**Comment by zmelamed** [comment]
@Timo614 we just got feedback from the venue that being able to add a 3rd party promoter to specific events is super high priority. Can you update me on where you are with this and how far we may be from delivering big-neon/bn-api#951

Is there a way to fast track this?

Wanted to get your thoughts on some possible alternate path (which we will likely do in addition to this):
Promoter access links: an org being able to goto Event Dashboard->Tools->Share event access->Create promoter link and password
- A quick solution to share access to the event dashboard so a promoter can view event stats with a read-only link
- A quick solution to share access to the full event management with a manager link

**Comment by Timo614** [comment]
@zmelamed I'm pretty close to having it set. Will adjust it re your feedback above in the morning.

Originally was going the direction of having a new role where we'd be able to update a list of event_ids the user had access to. May be worth adjusting that approach in light of the above link approach to granting access (since we wouldn't tie it down to an individual user then). 

I'll push what I've been working up to my branch tonight but will probably wait until tomorrow to push up the PR since it's getting late here.

**Comment by zmelamed** [comment]
If you feel just about ready with the work to have a new role that would take a list of event ids then drive that to the finish line

I think there are use cases that will justify having the link method in addition to the full fledged role method, but we can approach that link method later if the role version is ready to go.

Can you create a Promoter and Promoter Read Only role. 

Both would have access to everything an OrgMember role would related to the events they have permissions to access, except: wouldn’t be able to view any org level reports, org level fan list, etc. but the client side can restrict access to a lot of that, and wouldn’t be able to modify tickets or cancel the event.

The Read only role wouldn’t be able to edit any aspect of the event, holds, etc. just able to view.

Does that make sense?

**Comment by Timo614** [comment]
Sounds good, will do.

**Comment by mikethetike** [comment]
Technically it is possible to create a link of the format `/events/{id}?token={jwttoken}` (or shortened) and then when the user clicks on it, we use that token to interact with the page instead of retrieving from the db. @Timo614 , keep this in mind as an option. 

I'm happy with the way you have done it in your branch though
