### ISSUE TITLE
Fan Profile - Add Attendance Info

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-api#963]

**Comment by Timo614** [comment]
Is there a mockup of what information we want for attendance? Just want to make sure I include the right info. I noticed bn-web has a placeholder for rendering this:
https://github.com/big-neon/bn-web/blob/c8e35b8dd4e65eae3141dbdf7fab8199d6c2128a/src/components/pages/admin/fans/FanDetails.js#L261

**Comment by Timo614** [comment]
Let me know if we want to adjust this but for now will have the `attendance_information` field of the `FanProfile` return a vector that contains the `event_id` and `event_name` of any event where the user had a redeemed ticket instance associated with their wallet (so that if they transfer it after purchase it will count for whoever currently owns it).
